using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using XeptKit.Core;

namespace XeptKit.Localization
{
    /// <summary>
    /// 从本地化 Key 集合生成 C# const string 常量类（LocKeys.cs）。
    /// </summary>
    /// <remarks>
    /// 生成文件放置在业务指定输出目录（键属项目内容而非 Kit API，勿生成进 Assets/XeptKit/）。
    /// 命名空间固定 <c>XeptKit.Localization</c>（业务 using 该命名空间即获得 LocKeys，
    /// 查表经组合根持有的 <c>ILocalizationManager</c> 实例）。
    /// Key 名转换为 PascalCase（<c>menu_start</c> → <c>MenuStart</c>）；const string 编译期内联，
    /// 拼写错误即编译错误——这是该设计的核心价值，取代裸字符串查表。
    /// 两个 key 映射到同一 PascalCase（如 <c>menu_start</c> 与 <c>menuStart</c>）时记 Warning（不静默丢键）。
    /// </remarks>
    public static class LocKeysGenerator
    {
        /// <summary>
        /// 生成 LocKeys.cs 文件。
        /// </summary>
        /// <param name="outputDir">输出目录的绝对路径（须已存在；不存在由调用方创建或失败暴露）。</param>
        /// <param name="keys">所有本地化键的集合（可含重复/空键，生成器自行去重与跳过）。</param>
        /// <returns>成功生成的常量数量（键碰撞时小于实际键数）。</returns>
        public static int Generate(string outputDir, IReadOnlyCollection<string> keys)
        {
            Guard.NotNullOrEmpty(outputDir, nameof(outputDir));
            Guard.NotNull(keys, nameof(keys));

            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by XeptKit.Localization.LocKeysGenerator. DO NOT EDIT MANUALLY.");
            sb.AppendLine("// Re-import the localization CSV to regenerate.");
            sb.AppendLine();
            sb.AppendLine("namespace XeptKit.Localization");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 本地化键常量——编译时内联，零运行时开销。");
            sb.AppendLine("    /// 拼写错误即编译错误，取代裸字符串查表。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class LocKeys");
            sb.AppendLine("    {");

            var seen = new HashSet<string>(StringComparer.Ordinal);
            int generated = 0;
            foreach (var key in keys)
            {
                if (string.IsNullOrEmpty(key))
                {
                    continue;
                }

                var pascalKey = ToPascalCase(key);
                if (!seen.Add(pascalKey))
                {
                    Log.Warning(
                        $"[LocKeysGenerator] 键 \"{key}\" 与已有键映射到同一常量名 \"{pascalKey}\"，已跳过。");
                    continue;
                }

                sb.AppendLine($"        public const string {pascalKey} = \"{EscapeString(key)}\";");
                generated++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var filePath = Path.Combine(outputDir, "LocKeys.cs");
            File.WriteAllText(filePath, sb.ToString());
            return generated;
        }

        /// <summary>
        /// 将下划线/连字符/点/空格分隔的 key 转换为 PascalCase。
        /// </summary>
        /// <example>
        /// "menu_start" → "MenuStart"
        /// "hud_player_hp" → "HudPlayerHp"
        /// "item.rock.name" → "ItemRockName"
        /// "npc_dialog_choice_1" → "NpcDialogChoice1"
        /// </example>
        private static string ToPascalCase(string key)
        {
            var parts = key.Split(new[] { '_', '-', ' ', '.' }, StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();

            for (int i = 0; i < parts.Length; i++)
            {
                var part = parts[i];
                if (part.Length == 0)
                {
                    continue;
                }

                sb.Append(char.ToUpperInvariant(part[0]));
                if (part.Length > 1)
                {
                    sb.Append(part.Substring(1).ToLowerInvariant());
                }
            }

            var result = sb.ToString();
            if (result.Length == 0)
            {
                return "_" + key.Replace("-", "_").Replace(" ", "_");
            }

            // 若首字符为数字，前加下划线使其成为合法 C# 标识符
            if (char.IsDigit(result[0]))
            {
                result = "_" + result;
            }

            return result;
        }

        /// <summary>转义字符串中的 C# 特殊字符（反斜杠、双引号）。</summary>
        private static string EscapeString(string key)
        {
            return key.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
