// Auto-generated by XeptKit.Localization.LocKeysGenerator. DO NOT EDIT MANUALLY.
// Re-import the localization CSV to regenerate.

namespace XeptKit.Localization
{
    /// <summary>
    /// 本地化键常量——编译时内联，零运行时开销。
    /// 拼写错误即编译错误，取代裸字符串查表。
    /// </summary>
    public static class LocKeys
    {
        public const string ItemRockName = "item.rock.name";
        public const string ItemDrugName = "item.drug.name";
        public const string ItemFireaxeName = "item.fireaxe.name";
        public const string ItemBandgaeName = "item.bandgae.name";
        public const string ItemStoneName = "item.stone.name";
        public const string ItemBackpackName = "item.backpack.name";
        public const string InteractionPickup = "interaction.pickup";
        public const string InteractionIgnite = "interaction.ignite";
        public const string InteractionExtinguish = "interaction.extinguish";
        public const string InteractionAddfuel = "interaction.addfuel";
        public const string InteractionDebug = "interaction.debug";
        public const string InteractionWear = "interaction.wear";
        public const string InteractionEquip = "interaction.equip";
        public const string CampfireName = "campfire.name";
    }
}
